### ISSUE TITLE
Any Chance You will work on it ? 

### ISSUE THREAD

**Issue by xXRainbowXx24** [TLeonardUK/ds2os#12]
Its so sad thats the servers are down

**Comment by TLeonardUK** [comment]
As per the other issues. I'm not intending on putting any effort in until I see what From intends to do when they bring back the server.

Not going to waste my time if they just intend to slap EAC or something on the game.

**Comment by Jokler** [comment]
Would the addition of EAC be a roadblock for this project that can't easily be sidestepped? I don't know much about EAC but the Elden Ring [Seamless Co-op](https://www.nexusmods.com/eldenring/mods/510) mod "just" turns it off.

**Comment by DenisNovac** [comment]
Looks like they bring SOTFS back today, not sure if any anti-cheat included

**Comment by rorp24** [comment]
As shown [here](https://www.reddit.com/r/DarkSouls2/comments/ydnv76/critical_patch_info_fromsoft_left_in_the_majority/), the devs haven't fixed anythings, so peoples that just want to play with friends and not being hacked would love to have a dedicated server.

Also where can we give you some money, because you deserve it

**Comment by DenisNovac** [comment]
@rorp24 can't believe they come up with such poor "fix" after a half of the year.

**Comment by TLeonardUK** [comment]
Dark Souls 2 support is being integrated directly into DS3OS, see https://github.com/TLeonardUK/ds3os for details.

Closing down all tickets and archiving this repo.
